function FAQ() {
    const [openIndex, setOpenIndex] = React.useState(null);

    const faqs = [
        {
            question: "How does the AI portfolio generator work?",
            answer: "Our AI analyzes your content, work samples, and professional background to automatically create a tailored portfolio layout. It optimizes the presentation of your work while maintaining your personal style and professional identity."
        },
        {
            question: "Can I customize the AI-generated portfolio?",
            answer: "Yes, absolutely! While the AI creates an initial optimized layout, you have full control to customize every aspect of your portfolio, from colors and fonts to layout and content organization."
        },
        {
            question: "How long does it take to generate a portfolio?",
            answer: "The initial AI-generated portfolio is ready in just a few minutes after you upload your content. You can then make adjustments and refinements as needed."
        },
        {
            question: "What types of professionals can use this tool?",
            answer: "Our AI portfolio generator is designed for various professionals, including developers, designers, photographers, writers, business professionals, and anyone who wants to showcase their work online."
        },
        {
            question: "Is my portfolio mobile-responsive?",
            answer: "Yes, all portfolios generated by our AI are fully responsive and look great on all devices, from smartphones to desktop computers."
        },
        {
            question: "What are the pricing plans available?",
            answer: "We offer a free tier that includes basic portfolio features, and premium plans starting at $9/month that include advanced AI features, custom domains, and priority support. All plans come with a 14-day free trial."
        },
        {
            question: "Can I export my portfolio or use my own domain?",
            answer: "Yes! Premium users can export their portfolios or connect their own custom domains. We provide full DNS management support and SSL certificates for all custom domains."
        },
        {
            question: "How secure is my portfolio data?",
            answer: "We take security seriously. All data is encrypted both in transit and at rest, backed up regularly, and stored in secure cloud infrastructure. We also provide two-factor authentication for additional account security."
        }
    ];

    const toggleFAQ = (index) => {
        setOpenIndex(openIndex === index ? null : index);
    };

    return (
        <section data-name="faq" id="faq" className="py-20 bg-white">
            <div className="container mx-auto px-6">
                <h2 data-name="faq-title" className="text-3xl font-bold text-center mb-12">
                    Frequently Asked Questions
                </h2>
                <div className="max-w-3xl mx-auto">
                    {faqs.map((faq, index) => (
                        <div 
                            key={index}
                            data-name={`faq-item-${index}`}
                            className="mb-4"
                        >
                            <button
                                className="flex justify-between items-center w-full p-4 bg-gray-50 hover:bg-gray-100 rounded-lg focus:outline-none"
                                onClick={() => toggleFAQ(index)}
                            >
                                <span className="font-semibold text-left">{faq.question}</span>
                                <i className={`fas ${openIndex === index ? 'fa-chevron-up' : 'fa-chevron-down'} transition-transform duration-300`}></i>
                            </button>
                            <div 
                                className={`transition-all duration-300 overflow-hidden ${openIndex === index ? 'max-h-96 opacity-100' : 'max-h-0 opacity-0'}`}
                            >
                                <p className="p-4 text-gray-600">
                                    {faq.answer}
                                </p>
                            </div>
                        </div>
                    ))}
                </div>
            </div>
        </section>
    );
}
